### ISSUE TITLE
旋转缩放问题

### ISSUE THREAD

**Issue by 251068550** [CrawlerChaos/MoveScaleRotateView#1]
你好，如果图片是以初始角度开始旋转和缩放是没问题的，但是在2，3，4象限里开始触摸并旋转缩放就出现问题了，请问是怎么回事，能解决这个问题吗？

**Comment by CrawlerChaos** [comment]
没太明白

**Comment by 251068550** [comment]
你试着把图片旋转180°，放开手之后在重新旋转和放大就出问题了。不过我测试了下，是因为旋转后获得的中心点不正确导致的。

**Comment by CrawlerChaos** [comment]
I  see，我会修复这个问题，谢谢反馈。

**Comment by CrawlerChaos** [comment]
@251068550   bug fixed
